on:
  push:
    branches:
      - main    
  pull_request:
jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v1      
    - name: Run Continuous Integration
      shell: pwsh
      run : |
        cd ./__tests__
        Invoke-Pester -Output Detailed